version: "2.1"
services:
  emapi:
    build:
      context: ../em-api
    volumes:
      - ../em-api/config:/opt/data/nics/config/

  nicsweb:
    build:
      context: ../nics-web
    volumes:
      - ../nics-web/config:/opt/data/nics/config/

  openam:
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/openam:dev-latest
