version: "2.1"
services:
  emapi:
    build:
      context: ../em-api
      dockerfile: ../em-api/dev-Dockerfile

  nicsweb:
    build:
      context: ../nics-web
      dockerfile: ../nics-web/dev-Dockerfile

  openam:
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/openam:dev-latest
