version: "3"
services:
  emapi:
    container_name: nics_emapi_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/emapi:e1cfd9e
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    depends_on:
      - geoserver
      - postgis
      - rabbitmq
      - openam
    ports:
      - "7083:8000"
      - "8083:8080"
    volumes:
      - static:/var/lib/emapi/

  geoserver:
    container_name: nics_geoserver_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/geoserver:latest
    depends_on:
      - postgis
    ports:
      - "8084:8080"

  nicsweb:
    container_name: nics_nicsweb_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/nicsweb:60b05bb
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    depends_on:
      - emapi
      - openam
      - rabbitmq
    ports:
      - "7082:8000"
      - "8082:8080"

  postgis:
    container_name: nics_postgis_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/postgis:latest
    ports:
      - "5432:5432"

  proxy:
    container_name: nics_proxy_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/proxy:latest
    ports:
      - "3000:80"
      - "3443:443"
    depends_on:
      - web
    networks:
      default:
        aliases:
          - www.nicsdev.tabordasolutions.net

  rabbitmq:
    container_name: nics_rabbitmq_1
    image: rabbitmq:management
    hostname: nicsrabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    container_name: nics_web_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/web:latest
    depends_on:
      - emapi
      - geoserver
      - openam
      - nicsweb
    ports:
      - "8081:80"
    volumes:
      - static:/var/www/html/

  openam:
    container_name: nics_openam_1
    image: 618209257270.dkr.ecr.us-west-2.amazonaws.com/nics/openam:latest
    hostname: am.nicsdev.tabordasolutions.net
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8443:8443"
    networks:
      default:
        aliases:
          - am.nicsdev.tabordasolutions.net

volumes:
  static:
